### ISSUE TITLE
Feature/Request/Update: Port to RIFT for 1.13.2+

### ISSUE THREAD

**Issue by Xeddius** [Minebench/ZoMBe#3]
Given that it may be quite a long time before MCP is released for 1.13.2 and Liteloader (Dependent on mcp), it may be a wise course of action to migrate to the RIFT mod loader for the time being, it's a lightweight api and many other mods have already been ported over. (VoxelMap for example) I believe this to be the best course of action for the time being.

Rift can be found at:
`https://minecraft.curseforge.com/projects/rift`

It should also make updates much easier.

### Making mods work in many Minecraft versions

> With Rift, your mods will work throughout many Minecraft versions. Through optional mod compatibility modules, Rift will remap mods to updated obfuscated names and inject unimplemented vanilla methods back into classes, making the unstable Minecraft API stable. Although compatibility of all mods across many Minecraft versions may not be possible, most mods should work for at least a few versions.

**Comment by Phoenix616** [comment]
Unless the Macro and Keybind mod gets updated to Rift (or a similar mod is available with the ability to easily import existing configs) I see no use in moving to a different mod loader as that one is essential for me and my team.

I'm always open for PRs though if they are done in a way that leave the ability to easily support a different modloader in the future but I personally will probably not invest any work as long as I end up only with half of the functionality. (Besides the fact that mcp for 1.13.2 will probably be available very soon as 1.13.1 took ~1 1/2 months)

**Comment by Phoenix616** [comment]
Probably going to move to fabric once 1.14.x gets more stable and LiteLoader doesn't receive any surprise updates. Seeing as ViaVersion works pretty well I would suggest to use 1.14.x on 1.13.x servers then if that is required.

**Comment by Xeddius** [comment]
The difficulty with this is that my client has to be on 1.13.2 as that is the version of the client-mods I use. After Liteloader stopped updating most of them have migrated to Rift. Nothing currently runs on 1.14, though I am thankful you've brought ViaVersion to my attention as this might prove useful in the next 6-12 months. In the meantime I've managed to find an alternate Zombe style plugin to achieve what I need. Which combined with DaFlight has managed to supplant ZoMBe for the time being.
